spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/webshop?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=CET
    password: root
  jpa:
    show-sql: 'false'

logging:
  level:
    root: info
  file:
    path: logs


app:
  name: webshop
  email: ${EMAIL}
  password: ${PASSWORD}
  cors:
    allowedOrigins: http://localhost:4200, http://localhost:8080
  auth:
    tokenSecret: privatluk # lijen za generisanje secret-a
    tokenExpirationMillis: 86400000
