
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost/webshop?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=CET
    password: root
  jpa:
    show-sql: 'false'

server:
  port: ${PORT:8080}
  compression:
    enabled: true
    min-response-size: 1024 # min size to use compression for responses

app:
  imagesDir: "images"
  image:
    avatarDir: "avatars"
    productsDir: "products"


  name: webshop
  email: ${EMAIL}
  clientSecretPath: /client_secret.json
  cors:
    allowedOrigins: http://localhost:4200, http://localhost:8080
  auth:
    tokenSecret: privatluk # lijen za generisanje secret-a
    tokenExpirationMillis: 86400000

logging:
  level:
    root: info  #TRACE
  file:
    path: logs
